//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public Mail()
        {
            this.Attaches = new HashSet<Attach>();
        }
    
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Content { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Attach> Attaches { get; set; }
    }
}
